# Site settings
title: Art by Ann
email: dreaqu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Selections of original artwork by a tinkerer of all sorts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dreaqu.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
#permalink: pretty
permalink: /:title


plugins:
  - jekyll-assets

assets:
  compress:
    css: sass
    js: uglifier

  cache: false

  autoprefixer:
    browsers: ["last 2 versions","> 5%","IE 9"]

collections_dir: portfolio

collections:
  portfolio:
    output: true
    permalink: /:collection/:path
